// Code generated by timoni.
// Note that this file must have no imports and all values must be concrete.

@if(!debug)

package main

// Placeholder for CRD spec.
values: {
	spec: {
		instances: 1
		storage: size: "1Gi"
	}
}
