name: Release and sign modules
on:
  push:
    tags: [ '*' ] # has to be semver format

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access
  id-token: write # needed for signing

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cosign
        uses: sigstore/cosign-installer@main
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Vet, push and sign CRD blueprint
        run: |
          timoni mod push ./blueprints/crd \
            oci://ghcr.io/lion7/timoni-modules/blueprints/crd \
            --version ${{ github.ref_name }} \
            --latest \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            -a 'org.opencontainers.image.source=https://github.com/lion7/timoni-modules' \
            -a 'org.opencontainers.image.description=CRD blueprint for timoni.sh modules.' \
            -a 'org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/blueprints/crd/README.md'
      - name: Vet, push and sign bridge-cni module
        run: |
          timoni mod vet ./bridge-cni
          timoni mod push ./bridge-cni \
            oci://ghcr.io/${{ github.repository_owner }}/timoni-modules/bridge-cni \
            --version ${{ github.ref_name }} \
            --latest \
            --sign=cosign \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
            -a 'org.opencontainers.image.description=A timoni.sh module for configuring bridge-cni.' \
            -a 'org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/bridge-cni/README.md'
      - name: Vet, push and sign CRD modules
        run: |
          cd crd
          for module in */*; do
            group=$(dirname $module)
            name=$(basename $module)
            timoni mod vet ./$module
            timoni mod push ./$module \
              oci://ghcr.io/${{ github.repository_owner }}/timoni-modules/$group/$name \
              --version ${{ github.ref_name }} \
              --latest \
              --sign=cosign \
              -a "org.opencontainers.image.licenses=Apache-2.0" \
              -a "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
              -a "org.opencontainers.image.description=A timoni.sh module for $group/$name." \
              -a "org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/crd/$group/$name/README.md"
          done
