name: Release and sign modules
on:
  push:
    tags: [ '*' ] # has to be semver format

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access
  id-token: write # needed for signing

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cosign
        uses: sigstore/cosign-installer@main
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Vet modules
        run: |
          timoni mod vet ./metallb-ipaddresspool
          timoni mod vet ./bridge-cni
      - name: Push and sign modules
        run: |
          timoni mod push ./metallb-ipaddresspool \
            oci://ghcr.io/${{ github.repository_owner }}/modules/metallb-ipaddresspool \
            --version ${{ github.ref_name }} \
            --latest \
            --sign=cosign \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
            -a 'org.opencontainers.image.description=A timoni.sh module for configuring MetalLB.' \
            -a 'org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/metallb-ipaddresspool/README.md'
          timoni mod push ./cert-manager-clusterissuer \
            oci://ghcr.io/${{ github.repository_owner }}/modules/cert-manager-clusterissuer \
            --version ${{ github.ref_name }} \
            --latest \
            --sign=cosign \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
            -a 'org.opencontainers.image.description=A timoni.sh module for configuring cert-manager.' \
            -a 'org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/cert-manager-clusterissuer/README.md'
          timoni mod push ./bridge-cni \
            oci://ghcr.io/${{ github.repository_owner }}/modules/bridge-cni \
            --version ${{ github.ref_name }} \
            --latest \
            --sign=cosign \
            -a 'org.opencontainers.image.licenses=Apache-2.0' \
            -a 'org.opencontainers.image.source=https://github.com/${{ github.repository }}' \
            -a 'org.opencontainers.image.description=A timoni.sh module for configuring bridge-cni.' \
            -a 'org.opencontainers.image.documentation=https://github.com/lion7/timoni-modules/blob/main/bridge-cni/README.md'
